### ISSUE TITLE
Should line length limit be a soft or hard rule?

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/code-style#6]
In https://github.com/OpenZeppelin/openzeppelin-solidity/pull/944 the question came up whether the line length limit should trigger an error or a warning.

I am strongly against making it an error. It should be a soft rule to nudge people in the right direction, but not something that should be strictly enforced.

Here is an interesting talk about the tyranny of style guides, which eventually had to be shared in this repository: 
[Raymond Hettinger - Beyond PEP 8 -- Best practices for beautiful intelligible code - PyCon 2015](https://www.youtube.com/watch?v=wf-BqAjZb8M).

In attempting to stay below the line length limit, a programmer could turn to using one-letter variable names. In this case I prefer a longer line with more meaningful variable names.

@elopio presents the argument that warnings will be ignored and accumulate over time. I agree with this, but in such a case we should consider removing the rule.

**Comment by elopio** [comment]
I added that to my watchlist, thanks for the link.

Your argument about one-letter variable names is something that we catch on PR reviews. I hate short variable names, so that could also be part of our style guide, just human enforced.

I'll move it to warning. For now, because I still disagree, but let's leave that discussion for our future selves to handle. What I would like is my refactor branch to land, before getting into messy merge conflicts.

Leaving this open for more opinions to come and untie...

**Comment by frangio** [comment]
This will be solved by the use of Prettier in https://github.com/OpenZeppelin/code-style/pull/19.
